# Header
menu:
  Home:  /silentsong
  Archives: /silentsong/archives
rss: /silentsong/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /silentsong/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# baidu_statistics
baidu_statistics:
favicon: /silentsong/favicon.png
